version: "3"
services:
  web:
    image: tsuru-kame
    build: .
    container_name: tsuru-kame
    working_dir: /app
    volumes:
      - /C/Projects/tsuru-kame:/app
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    tty: true
